demo:
  - any: ["examples", "elements/*/demo"]

doc:
  - any: ["docs", "elements/**/*.{md,txt}"]

functionality:
  - any: ["elements/*/src/*.js"]

styles:
  - any: ["elements/*/src/*.{scss,css}", "tokens"]

tests:
  - any: ["elements/*/test"]

tools:
  - any:
      [
        "scripts",
        "elements/*/gulpfile.js",
        "elements/*/rollup.config.js",
        "./.*",
        "./*.{js,json,yml}",
      ]
